# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Halt and Catch Fire
tagline:          'Random notes'
description:      ''
url:              http://notes.kartashov.com
baseurl:          /

author:
  name:           'Vasily Kartashov'
  url:            https://twitter.com/__kartashov

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vasily-kartashov/vasily-kartashov.github.io
