# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Бортовой журнал
tagline:          'Random notes'
description:      ''
url:              http://notes.kartashov.com
baseurl:          '/'

author:
  name:           'Vasily Kartashov'
  url:            https://twitter.com/__kartashov

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vasily-kartashov/vasily-kartashov.github.io

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]